### ISSUE TITLE
Server Crashes with this mod

### ISSUE THREAD

**Issue by AtaqanKurt** [RayTrace082/untamedwilds#24]
[latest.log](https://github.com/RayTrace082/untamedwilds/files/6722400/latest.log)

**Comment by AtaqanKurt** [comment]
it works on singleplayer launcher but crashes the server.

**Comment by RayTrace082** [comment]
Can't replicate this one, one of the letters in the "kingsnake" resource location has been replaced with a non-alphabet character (ý). I have implemented a possible solution for it, and it seems to work in-dev

If you don't mind answering, are you using any Resource Pack? do you use English (US) as a language in Minecraft? Is your operating system in a language featuring the ý character?

**Comment by AtaqanKurt** [comment]
im using my pc in turkish but turkish doesnt have that character and i dont use any resource packs and my minecraft is english

**Comment by RayTrace082** [comment]
Forgot to mention, but I did update the mod with a hotfix, which includes a possible solution for your problem

Fingers crossed

**Comment by CaptainFexis** [comment]
> 
> 
> Forgot to mention, but I did update the mod with a hotfix, which includes a possible solution for your problem
> 
> Fingers crossed

I couldnt make the mod work still... Yes, im using the latest version of it and getting the excatly same error.

**Comment by CaptainFexis** [comment]
> 
> 
> Forgot to mention, but I did update the mod with a hotfix, which includes a possible solution for your problem
> 
> Fingers crossed

[crash-2021-08-20_16.53.26-fml.txt](https://github.com/RayTrace082/untamedwilds/files/7022042/crash-2021-08-20_16.53.26-fml.txt)
Im using the last version but still getting the ''character in path of location: untamedwilds:egg_tarantula_black_and_whıte'' error

**Comment by JohnVeritas** [comment]
Hello, I just downloaded latest untamedwilds mod from curseforge looks like this problem is still there. 

`-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
-- MOD untamedwilds --
Details:
	Mod File: untamedwilds-1.16.5-1.4.1.jar
	Failure message: Untamed Wilds (untamedwilds) has failed to load correctly
		net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: untamedwilds:egg_tarantula_black_and_whıte
	Mod Version: 1.4.1
	Mod Issue URL: https://github.com/RayTrace082/untamedwilds/issues
	Exception message: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: untamedwilds:egg_tarantula_black_and_whıte
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:114) ~[forge:?] {re:classloading}
	at untamedwilds.init.ModItems.registerSpawnItems(ModItems.java:106) ~[untamedwilds:1.16.5-1.4.1] {re:classloading}
	at untamedwilds.UntamedWilds.<init>(UntamedWilds.java:55) ~[untamedwilds:1.16.5-1.4.1] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_311] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_311] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_311] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_311] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_311] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_311] {}

`
I'm using my windows langauge as Turkish as like the OP. And I have a little clue about this problem. See in Turkish language, we have 29 letters in the alphabet. And we have special letters like "ı ğ ü ş ç ö"  The letter (ý) is decoded as (ı) in this matter. From what I see its decoded as "whıte" while its supposed to be "whýte" this might be cause the problem, I hope this info could help you. Keep up your good work we're waiting for a fix thx.

**Comment by RayTrace082** [comment]
At this point I don't have a god damn clue about what causes this shit, random letters being replaced with others that look *almost* the same, but are not part of the alphabet

The good news is that I have reworked everything to do with variants, and the Items that seem to caused this issue (the dynamically created mobs eggs/spawn items) don't exist anymore, and are now condensed into one single Item with NBT data and custom models to keep the visuals unique

Fingers crossed that this bug is gone for good

**Comment by JohnVeritas** [comment]
Oh I tought it'll took several days for get an answer but a solution already? Damn thank you man! You really care about your project it's nice to see that. Btw, when I changed my windows language to english I had no problem with the mod. I will update the mod and try it on Turkish language and let you know if its solved or not.

**Comment by Atopik2** [comment]
i have the same problem keeping me from using this awesome mod in my modpack im using turkish too

**Comment by Atopik2** [comment]
it just crashes on startup saying that there is a non a-z character in the files ;untamedwilds:egg_trevally_bıgeye notice its ı not i and yes the turk'sh alphabet has that letter 'm us'ng 1/4/1

**Comment by Atopik2** [comment]
@JohnVeritas

**Comment by RayTrace082** [comment]
This bug is *probably* fixed in the latest alpha version (1.5.0), try that one instead

Didn't close the issue just in case of further issues on the subject, but the whole system that caused this crash (dynamic item instances) got axed

**Comment by justliliandev** [comment]
@RayTrace082 the error is happening on the i without a dot. That happens when you try to make a string to a lowercase String and you either don't add a locale as a parameter or add the wrong one. Eventhough the error doesn't appear I suggest you to use Locale.ENGLISH for any resourcelocation specific tasks in the future

**Comment by GAIIGE** [comment]
Ive had an issue with it crashing my server, the snakes keep crashing when rendering, or when struck by a snowball or something not lethal. ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/30/21 6:45 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at untamedwilds.entity.reptile.EntitySnake.isRattler(EntitySnake.java:170) ~[?:1.16.5-1.5.0] {re:classloading}
	at untamedwilds.client.model.ModelSnake.setRotationAngles(ModelSnake.java:181) ~[?:1.16.5-1.5.0] {re:classloading}
	at untamedwilds.client.model.ModelSnake.func_225597_a_(ModelSnake.java:11) ~[?:1.16.5-1.5.0] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:111) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:43) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:18) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinEntityRendererManager,pl:mixin:APP:quark.mixins.json:client.EntityRendererManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.21.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$492/401194142.call(Unknown Source) [forge-1.16.5-36.2.21.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at untamedwilds.entity.reptile.EntitySnake.isRattler(EntitySnake.java:170) ~[?:1.16.5-1.5.0] {re:classloading}
	at untamedwilds.client.model.ModelSnake.setRotationAngles(ModelSnake.java:181) ~[?:1.16.5-1.5.0] {re:classloading}
	at untamedwilds.client.model.ModelSnake.func_225597_a_(ModelSnake.java:11) ~[?:1.16.5-1.5.0] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:111) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:43) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:18) ~[?:?] {re:classloading,re:mixin}
-- Entity being rendered --
Details:
	Entity Type: untamedwilds:snake (untamedwilds.entity.reptile.EntitySnake)
	Entity ID: 34317
	Entity Name: Snake
	Entity's Exact location: 389.58, 69.00, -1267.34
	Entity's Block location: World: (389,69,-1268), Chunk: (at 5,4,12 in 24,-80; contains blocks 384,0,-1280 to 399,255,-1265), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Entity's Momentum: -0.02, 0.28, 0.22
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: untamedwilds.client.render.RendererSnake@371d0c83
	Location: -0.06,-1.62,0.69 - World: (-1,-2,0), Chunk: (at 15,-1,0 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -14.743735
	Delta: 0.7400073
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinEntityRendererManager,pl:mixin:APP:quark.mixins.json:client.EntityRendererManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Gaiige'/34211, l='ClientLevel', x=389.64, y=69.00, z=-1268.02]]
	Chunk stats: Client Chunk Cache: 441, 246
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,63,-78), Chunk: (at 0,3,2 in 15,-5; contains blocks 240,0,-80 to 255,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1418931 game time, 1569494 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.21.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$492/401194142.call(Unknown Source) [forge-1.16.5-36.2.21.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1462555904 bytes (1394 MB) / 3868196864 bytes (3689 MB) up to 5607784448 bytes (5348 MB)
	CPUs: 6
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6016m -Xms256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.21.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.21.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.21.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.21.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.21.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.21
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		CosmicNPCs-1.16.4-1.3.0.jar                       |CosmicNPCs                    |cosmicnpcs                    |1.3.0               |DONE      |Manifest: NOSIGNATURE
		infernal-expansion-1.16.5-2.4.0.jar               |Infernal Expansion            |infernalexp                   |2.4.0               |DONE      |Manifest: NOSIGNATURE
		bagofyurting-1.16.4-1.2.0.1.jar                   |Bag of Yurting                |bagofyurting                  |1.2.0.1             |DONE      |Manifest: NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.138.jar                          |Just Enough Items             |jei                           |7.7.1.138           |DONE      |Manifest: NOSIGNATURE
		VisualWorkbench-v1.1.0-1.16.5.jar                 |Visual Workbench              |visualworkbench               |1.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Architects-Palette-1.16.4-1.1.4.jar               |Architect's Palette           |architects_palette            |1.1.2               |DONE      |Manifest: NOSIGNATURE
		dungeons_mobs-1.16.5-1.0.10.jar                   |Dungeons Mobs                 |dungeons_mobs                 |1.0.10              |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.16.5-3.0.3.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.3               |DONE      |Manifest: NOSIGNATURE
		Enhanced-Mushrooms-1.16.5-3.0.9.jar               |Enhanced Mushrooms            |enhanced_mushrooms            |1.16.5-3.0.9        |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.6.0-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.6.0               |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.1.0.455.jar                    |Mekanism                      |mekanism                      |10.1.0              |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.16.5-7.2.2.0-build.0202.jar      |Forge Endertech               |forgeendertech                |7.2.2.0             |DONE      |Manifest: NOSIGNATURE
		Fallingleaves-1.16.3-1.2.2.jar                    |Falling Leaves                |fallingleaves                 |1.2.2-alpha+20211118|DONE      |Manifest: NOSIGNATURE
		mgui-1.16.5-3.3.0.jar                             |mgui                          |mgui                          |3.3.0               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |DONE      |Manifest: NOSIGNATURE
		untamedwilds-1.16.5-1.5.0.jar                     |Untamed Wilds                 |untamedwilds                  |1.5.0               |DONE      |Manifest: NOSIGNATURE
		smarterfarmers-1.16.5-1.2.1.jar                   |Smarter Farmers               |smarterfarmers                |1.16.5-1.2          |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |DONE      |Manifest: NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |DONE      |Manifest: NOSIGNATURE
		moreminecarts-1.3.12.jar                          |More Minecarts                |moreminecarts                 |1.3.12              |DONE      |Manifest: NOSIGNATURE
		environmental-1.16.5-1.1.1.jar                    |Environmental                 |environmental                 |1.1.1               |DONE      |Manifest: NOSIGNATURE
		AdHooks-1.16.5-6.1.8.0-build.0184.jar             |Advanced Hook Launchers       |adhooks                       |6.1.8.0             |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.3.29.jar                |Bookshelf                     |bookshelf                     |10.3.29             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		bamboo_blocks-1.16.5-3.0.1.jar                    |Bamboo Blocks                 |bamboo_blocks                 |3.0.1               |DONE      |Manifest: NOSIGNATURE
		pneumaticcraft-repressurized-1.16.5-2.14.6-277.jar|PneumaticCraft: Repressurized |pneumaticcraft                |1.16.5-2.14.6-277   |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.14.3.484.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.14.3.484   |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.16.5.1.2.6.jar                   |Guard Villagers               |guardvillagers                |1.2.6               |DONE      |Manifest: NOSIGNATURE
		DarkUtilities-1.16.5-8.0.10.jar                   |Dark Utilities                |darkutils                     |8.0.10              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		inventorypets-1.16.5-2.0.15.jar                   |Inventory Pets                |inventorypets                 |2.0.15              |DONE      |Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.3.0-10.jar            |Immersive Petroleum           |immersivepetroleum            |3.3.0-10            |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.21-universal.jar                |Forge                         |forge                         |36.2.21             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.18.0.jar                 |Supplementaries               |supplementaries               |0.18.0              |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.5-1.6.3.jar                   |BetterEnd Forge               |betterendforge                |1.16.5-1.6.3        |DONE      |Manifest: NOSIGNATURE
		neapolitan-1.16.5-2.2.1.jar                       |Neapolitan                    |neapolitan                    |2.2.1               |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |DONE      |Manifest: NOSIGNATURE
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		CraftingTweaks_1.16.5-12.2.1.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.21-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.2.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.2               |DONE      |Manifest: NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.5.4.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.5.4        |DONE      |Manifest: NOSIGNATURE
		Psi 1.16-97.jar                                   |Psi                           |psi                           |1.16-96             |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.7-143.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.7-143    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |DONE      |Manifest: NOSIGNATURE
		endremastered-forge-R4.1.1.jar                    |End Remastered                |endrem                        |4.1                 |DONE      |Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |DONE      |Manifest: NOSIGNATURE
		turtlemancy-1.16.5-1.6.3.jar                      |Turtlemancy                   |turtlemancy                   |1.6.3               |DONE      |Manifest: NOSIGNATURE
		Botania-1.16.5-420.1.jar                          |Botania                       |botania                       |1.16.5-420.1        |DONE      |Manifest: NOSIGNATURE
		darkerdepths-1.16.5-1.1.4.jar                     |Darker Depths                 |darkerdepths                  |1.1.4               |DONE      |Manifest: NOSIGNATURE
		atmospheric-1.16.5-3.1.1.jar                      |Atmospheric                   |atmospheric                   |3.1.1               |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		tetra-1.16.5-3.20.0.jar                           |Tetra                         |tetra                         |3.20.0              |DONE      |Manifest: NOSIGNATURE
		savageandravage-1.16.5-3.2.0.jar                  |Savage & Ravage               |savageandravage               |3.2.0               |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.6.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.6        |DONE      |Manifest: NOSIGNATURE
		autumnity-1.16.5-2.1.2.jar                        |Autumnity                     |autumnity                     |2.1.2               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-321.jar                                |Quark                         |quark                         |r2.4-321            |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.5.0.jar                   |Storage Drawers               |storagedrawers                |8.5.0               |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-2.11.3.jar                           |FramedBlocks                  |framedblocks                  |2.11.3              |DONE      |Manifest: NOSIGNATURE
		Runelic-1.16.5-7.0.2.jar                          |Runelic                       |runelic                       |7.0.2               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		fins-1.6.2.jar                                    |Fins and Tails                |fins                          |1.6.2               |DONE      |Manifest: NOSIGNATURE
		cavebiomeapi-1.16.5-1.4.2.jar                     |CaveBiomeAPI                  |cavebiomeapi                  |1.16.5-1.4.2        |DONE      |Manifest: NOSIGNATURE
		nethers_delight-2.1.jar                           |Nethers Delight               |nethers_delight               |2.1                 |DONE      |Manifest: NOSIGNATURE
		MarketCrates-1.16.4-35.1.4-v1.1-universal.jar     |Market Crates                 |marketcrates                  |v1.1-universal      |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.2.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.2.0      |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v1.0.15-1.16.5-Forge.jar               |Puzzles Lib                   |puzzleslib                    |1.0.15              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Aquaculture-1.16.5-2.1.21.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.21       |DONE      |Manifest: NOSIGNATURE
		enchantwithmob-1.16.5-1.5.2.jar                   |Enchant With Mob              |enchantwithmob                |1.16.5-1.5.2        |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.14.jar                        |Valhelsia Core                |valhelsia_core                |16.0.14             |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.6.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.6        |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		dungeons_gear-1.16.5-3.0.21-hotfix.jar            |Dungeons Gear                 |dungeons_gear                 |3.0.21-hotfix       |DONE      |Manifest: NOSIGNATURE
		Cyclic-1.16.5-1.5.13.jar                          |Cyclic                        |cyclic                        |1.16.5-1.5.13       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
	Crash Report UUID: 65e3e8c1-e911-4ef0-a4bf-9d9977f416eb
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Launched Version: forge-36.2.21
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.12, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz




I have tried to use the most recent update and also the last one as of 12/30/21.

**Comment by RayTrace082** [comment]
@agnor99 the thing that still baffles me is why some of the variants (all of which are alphanumeric names) had some random letters being randomly replaced by "looks almost the same, but it's not alphanumeric" characters from the computer owner's language, this was not the only instance of this happening

Anyway, removing the whole thing ended up being for the better

@GAIIGE Consider opening a new issue for this, since I am finally closing this one for good

Also, I can't replicate your issue, if you updated the mod from an old world to the latest alpha versions (1.5.X), they are not compatible
